### ISSUE TITLE
Fix trampoline overrides for excluded methods

### ISSUE THREAD

**Issue by kwabenantim** [jmsgrogan/cppwg#43]
From the yaml configuration below, a method definition is not generated for the excluded method `ClassFoo::MethodBar`. However, the pybind11 virtual function [trampoline overrides](https://pybind11.readthedocs.io/en/stable/advanced/classes.html) are still generated.

```yaml
  - name: module_foobar

    classes:
      - name: ClassFoo
        excluded_methods:
          - MethodBar
```
