### ISSUE TITLE
List unwrapped classes

### ISSUE THREAD

**Issue by kwabenantim** [jmsgrogan/cppwg#50]
## Summary
Create a list of class declarations that are found in the input headers but are not specified for wrapping in `package_info.yaml`.  This is useful in large projects for checking wrapper coverage.

Some classes may be purposefully excluded from wrapping -- it will be useful to have syntax to mark these classes in `package_info.yaml`.

Also, throw if a class specified in `package_info.yaml` is not declared in the input headers.

**Comment by kwabenantim** [comment]
The `excluded` setting can now be used in configuration to intentionally exclude classes from wrapping.

```yaml
name: pyshapes
modules:
  - name: primitives
    classes:
      - name: Triangle
         excluded: True
```

Classes found in the source tree that are not marked for wrapping or exclusion will appear in logs as
```
Unknown class <class_name> from <file_name>
```

The `--logfile` command line option can now be used to output logs to file.
